# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9ae86e6bd96b54799b5206cb8ba4c28f7e507db493d429506685e98926998e3bf63bd64f382d3c84156e46c428399facc14e0ec9c44743faf15c1a2642fee233

test:
  secret_key_base: 19e7c127d5775c6398f98833fd4dc4710f8497baf105330e6e116ddf4ca4b24452e59a343ed49da0392d28b4d7980f13f8011451a47e6177626176dbaba76a65

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
